project:
  output-dir: output
  type: website

website:
  title: "Presentation_TDA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



